weather:
  api:
    key: ${WEATHER_API_KEY}
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  main:
    allow-circular-references: true
  server:
    port: ${SERVER_PORT}
    servlet:
      context-path: /diaryDesk
  redis:
    data:
      host: ${REDIS_HOST}
      port: 15641
      password: ${REDIS_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: diaryDeskdb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA_EMAIL}
    password: ${JAVA_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  